= Spring Cloud Function with riff and Knative Workshop

== Results Sink Function App

Spring Boot App with Spring Cloud Function that writes incoming data to a Spanner database

This app image is published as `trisberg/resultssink-function` on Docker Hub.

If you want to re-create this app follow the steps outlined below.

=== Create the Spring Boot app

. Initialize the Boot app (You can also use https://start.spring.io/[Spring Initializr] web interface)
+
----
curl https://start.spring.io/starter.tgz \
  -d bootVersion=2.1.0.M3 \
  -d applicationName=ResultsSinkApp \
  -d dependencies=cloud-function,web,cloud-gcp \
  -d name=results-sink \
  -d artifactId=results-sink \
  -d baseDir=results-sink | tar -xzvf -
cd results-sink
----

. Add the GCP Spanner starter dependency (the bold parts are the additions):
+
.pom.xml
[source,subs=+quotes]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

...

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
		</dependency>
		*<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
		</dependency>*

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

...

</project>
----

. Add a `SpannerTemplate`, a Results class and a `@Bean` for the consumer (the bold parts are the additions):
+
.src/main/java/com.example.resultssink/ResultsSinkApp.java
[source,subs=+quotes]
----
package com.example.resultssink;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
*import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.cloud.gcp.data.spanner.core.mapping.Column;
import org.springframework.cloud.gcp.data.spanner.core.mapping.PrimaryKey;
import org.springframework.cloud.gcp.data.spanner.core.mapping.Table;
import java.util.function.Consumer;
import java.util.UUID;*

@SpringBootApplication
public class ResultsSinkApp {

	*@Autowired
	SpannerTemplate spannerTemplate;*

	*@Table(name = "results")
	public class Results {

		@PrimaryKey
		@Column(name = "id")
		UUID id;
		String name;
		String catnotcat;

		public Results(UUID id, String name, String catnotcat) {
			this.id = id;
			this.name = name;
			this.catnotcat = catnotcat;
		}
	}*

	*@Bean
	public Consumer<Message<String>> sink() {
		return (in) -> {
			String name = ""+in.getHeaders().get("ce-image-name");
			Results r = new Results(UUID.randomUUID(), name, in.getPayload());
			this.spannerTemplate.insert(r);
			System.out.println("Processed -> " + r.id + " : " + name);
		};
	}*

	public static void main(String[] args) {
		SpringApplication.run(ResultsSinkApp.class, args);
	}
}
----

. Add properties for connecting to the database.
+
.src/main/resources/application.properties
[source,subs=+quotes]
----
*spring.cloud.gcp.spanner.instance-id=workshop
spring.cloud.gcp.spanner.database=catnotcat*
----

. Add a schema file for creating the table.
+
.src/main/resources/schema.ddl
[source,subs=+quotes]
----
*CREATE TABLE results (
  id        STRING (36) NOT NULL,
  name      STRING (255) NOT NULL,
  catnotcat STRING (10) NOT NULL
) PRIMARY KEY (id );*
----

. Build the app and the Docker image using Jib  (change the image name when building your own)
+
----
./mvnw clean compile com.google.cloud.tools:jib-maven-plugin:build \
  -Dimage=trisberg/resultssink-function
----

=== Set up the GCP Spanner instance

. Enable Spanner and create an instance, a database and the table
+
----
gcloud services enable spanner.googleapis.com
gcloud spanner instances create workshop --config=regional-us-central1 \
  --nodes=1 --description="SpringOne Platform 2018"
gcloud spanner databases create catnotcat --instance=workshop
gcloud spanner databases ddl update catnotcat \
  --instance=workshop --ddl="$(cat ./src/main/resources/schema.ddl)"
----

=== Deploy the app to GKE

. Enable Egress to Google Cloud Platform APIs
+
----
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
EOF
----

. Enable Egress to Google Cloud Platform metadata
+
----
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: metadata-server
spec:
  hosts:
  - metadata.google.internal
  - 169.254.169.254
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
EOF
----

. Create the Knative service for the app
+
----
export GCP_PROJECT=$(gcloud config get-value core/project)
riff service create resultssink \
    --env SPRING_CLOUD_GCP_PROJECT_ID=${GCP_PROJECT} \
    --image trisberg/resultssink-function
----