= Spring Cloud Function with riff and Knative Workshop

== Results Sink Function App

Spring Boot App with Spring Cloud Function that writes incoming data to a Spanner database

This app image is published as `trisberg/resultssink-function` on Docker Hub.

If you want to re-create this app follow the steps outlined below.

=== Create the Spring Boot app

. Initialize the Boot app (You can also use https://start.spring.io/[Spring Initializr] web interface)
+
----
curl https://start.spring.io/starter.tgz \
  -d applicationName=ResultsSinkApp \
  -d dependencies=cloud-function,web,cloud-gcp \
  -d artifactId=results-sink \
  -d baseDir=results-sink | tar -xzvf -
cd results-sink
----

. Update the Spring Cloud GCP version and the dependencies for Spring Cloud Function and add the GCP Spanner starter and a Jib plugin (change the image name if you plan on building your own)(the bold parts are the additions):
+
.pom.xml
[source,subs=+quotes]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>results-sink</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.5.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud-gcp.version>1.0.0.RELEASE</spring-cloud-gcp.version>
		<spring-cloud.version>Finchley.SR1</spring-cloud.version>
		*<spring-cloud-gcp.version>1.1.0.M1</spring-cloud-gcp.version>
		<spring-cloud-function.version>2.0.0.BUILD-SNAPSHOT</spring-cloud-function.version>*
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
		</dependency>
		*<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
		</dependency>*

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			*<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-function-dependencies</artifactId>
				<version>${spring-cloud-function.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>*
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>${spring-cloud-gcp.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			*<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>0.9.10</version>
				<configuration>
					<to>
						<image>trisberg/resultssink-function</image>
					</to>
				</configuration>
			</plugin>*
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>


</project>
----

. Add a `SpannerTemplate`, a Results class and a `@Bean` for the function (the bold parts are the additions):
+
.src/main/java/com.example.resultssink/ResultsSinkApp.java
[source,subs=+quotes]
----
package com.example.resultssink;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
*import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate;
import org.springframework.context.annotation.Bean;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.cloud.gcp.data.spanner.core.mapping.Column;
import org.springframework.cloud.gcp.data.spanner.core.mapping.PrimaryKey;
import org.springframework.cloud.gcp.data.spanner.core.mapping.Table;
import java.util.function.Function;
import java.util.UUID;*

@SpringBootApplication
public class ResultsSinkApp {

	*@Autowired
	SpannerTemplate spannerTemplate;*

	*@Table(name = "results")
	public class Results {

		@PrimaryKey
		@Column(name = "id")
		UUID id;
		String name;
		String catnotcat;

		public Results(UUID id, String name, String catnotcat) {
			this.id = id;
			this.name = name;
			this.catnotcat = catnotcat;
		}
	}*

	*@Bean
	public Function<Message<String>, Message<String>> sink() {
		return (in) -> {
			String name = ""+in.getHeaders().get("ce-image-name");
			Results r = new Results(UUID.randomUUID(), name, in.getPayload());
			this.spannerTemplate.insert(r);
			return MessageBuilder.withPayload("Processed -> " + r.id + " : " + name).build();
		};
	}*

	public static void main(String[] args) {
		SpringApplication.run(ResultsSinkApp.class, args);
	}
}
----

. Add properties for connecting to the database.
+
.src/main/resources/application.properties
[source,subs=+quotes]
----
*spring.cloud.gcp.spanner.instance-id=workshop
spring.cloud.gcp.spanner.database=catnotcat*
----

. Add a schema file for creating the table.
+
.src/main/resources/schema.ddl
[source,subs=+quotes]
----
*CREATE TABLE results (
  id        STRING (36) NOT NULL,
  name      STRING (255) NOT NULL,
  catnotcat STRING (10) NOT NULL
) PRIMARY KEY (id );*
----

. Build the app and the Docker image 
+
----
./mvnw compile jib:build
----

=== Set up the GCP Spanner instance

. Enable Spanner and create an instance, a database and the table
+
----
gcloud services enable spanner.googleapis.com
gcloud spanner instances create workshop --config=regional-us-central1 \
  --nodes=1 --description="SpringOne Platform 2018"
gcloud spanner databases create catnotcat --instance=workshop
gcloud spanner databases ddl update catnotcat \
  --instance=workshop --ddl="$(cat ./src/main/resources/schema.ddl)"
----

=== Deploy the app to GKE

. Enable Egress to Google Cloud Platform APIs
+
----
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
spec:
  hosts:
  - "*.googleapis.com"
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTPS
EOF
----

. Create a service account and key
+
----
gcloud iam service-accounts create spanner-results
export GCP_PROJECT=$(gcloud config get-value core/project)
gcloud projects add-iam-policy-binding $GCP_PROJECT \
  --member serviceAccount:spanner-results@$GCP_PROJECT.iam.gserviceaccount.com \
  --role roles/spanner.databaseUser
gcloud iam service-accounts keys create \
  --iam-account "spanner-results@$GCP_PROJECT.iam.gserviceaccount.com" \
  ~/spanner-results.json
----

. Create the Knative service for the app
+
----
export GCP_PROJECT=$(gcloud config get-value core/project)
riff service create resultssink \
    --env SPRING_CLOUD_GCP_PROJECT_ID=${GCP_PROJECT} \
    --env SPRING_CLOUD_GCP_CREDENTIALS_ENCODED_KEY="$(base64 $HOME/spanner-results.json)" \
    --image trisberg/resultssink-function
----